FORMAT: 1A
HOST: https://horizon-testnet.stellar.org

# Horizon

*NOTE: Horizon is in very active development*

Horizon is the client facing API server for the Stellar network ecosystem.  See [an overview of the Stellar ecosystem](TODO) for more details.

Horizon provides (well, intends to provide when complete) two significant portions of functionality:  The Transactions API and the History API.

## Transactions API

The Transactions API exists to help you make transactions against the stellar network.  It provides ways to help you create valid transactions, such as providing an account's sequence number or latest known balances.

In addition to the read endpoints, the Transactions API also provides the endpoint to submit transactions.

### Future additions

The current capabilities of the Transactions API does not represent what will be available at the official launch of the new Stellar network.  Notable additions to come:

- Endpoints to read the current state of a given order book or books to aid in creating offer transactions
- Endpoints to calculate suitable paths for a payments

## History API

The History API provides endpoints for retrieving data about what has happened in the past on the stellar network.  It provides (or will provide) a endpoints that let you:

- Retrieve transaction details
- Load transactions that effect a given account
- Load payment history for an account
- Load trade history for a given order book


### Future additions

The history API is pretty sparse at present.  Presently you can page through all transactions in application order, or page through transactions that a apply to a single account.  This is really only useful for explaining how paging and filtering works within horizon, as most useful information for transactions are related to their operations.


## API Overview

The following section describes a couple of important concepts for the horizon api at a high level.  Understanding these concepts will help make your overall experience integrating with horizon much easier.

### Response Format

Rather than using a full custom way of representing the resources we expose in Horizon, we use [HAL](http://stateless.co/hal_specification.html). HAL is a simple hypermedia format in JSON that remains simple while giving us a couple of benefits such as simpler client integration for several languages. See [this wiki page](https://github.com/mikekelly/hal_specification/wiki/Libraries) for a list of libraries.

See [Responses](responses.md) for more details

### Error Format

HAL doesn't really have any special consideration for error responses.  To provide some standardization to our API's error messages we use the [Problem Details for HTTP APIs RFC](https://tools.ietf.org/html/draft-ietf-appsawg-http-problem-00)

See [errors](errors.md) for more details

### Paging

Some resources in horizon represent a collection of other resources.  Almost always, loading this collection in its entirety is not feasible.  To work around this, we provide a way to page through a collection.

The paging system in horizon is known as a _token-based_ paging system.  There is no "page 3" or the like.  Paging through a collection in a token-based paging system involves three pieces of data:

- the *paging token*, which is an opaque value that logically represents the last record seen by a client.
- the *limit*, or page size, a positive integer.
- the *order* applied to the whole collection

See [paging](paging.md) for more details.

## Ledger [/ledgers/{sequence}]

The Stellar network stores data in shared public ledger, and is changes by a series of transactions applied one after the other.  Each round of consensus produces a new ledger, identified by a sequence number.  The ledger resource represents a summary of a closed ledger and contains links to further details.

+ Attributes
  + id (string, required)                 - An opaque identifier for this resource
  + paging_token (string, required)       - An opaque cursor, which may be used for paging through the collection (i.e. used as the cursor parameter)
  + hash (string, required)               - The Hex-encoded hash of the ledger header
  + prev_hash (string, optional)          - The Hex-encoded hash of the ledger header preceding this ledger
  + sequence (number, required)           - This ledger's sequence number
  + transaction_count (number, required)  - The number of transactions that were validated and applied during the creation of this ledger
  + operations_count (number, required)   - The number of operations that were applied during the creation of this ledger
  + closed_at (Date, required)            - The time that this ledger was validated by the network and closed

### View ledger summary [GET]

+ Parameters

  + sequence: 123 (number, required) - A sequence number

+ Response 200

  + Attributes (Ledger)

## Account [/accounts/{address}]

Represents the current state of an account as of the latest closed
ledger imported by horizon.

+ Attributes
  + id (string, required)                 - An opaque identifier for this resource
  + paging_token (string, required)       - An opaque cursor, which may be used for paging through the collection (i.e. used as the cursor parameter)

### View account details [GET]

+ Parameters

  + address (required, string, `gjgPNE2GpySt5iYZaFFo1svCJ4gbHwXxUy8DDqeYTDK6UzsPTs`) ... Address of an account

+ Response 200

  + Attributes (Account)

## Transaction [/transactions/{hash}]

Represents a single transaction that has been submitted and validated by the stellar network

+ Attributes
  + id (string, required)                 - An opaque identifier for this resource
  + paging_token (string, required)       - An opaque cursor, which may be used for paging through the collection (i.e. used as the cursor parameter)
  + hash (string, required)             - Hex-encoded hash of the transaction
  + ledger (number, required)           - The ledger sequence in which this transaction was validated
  + account (string, required)          - The base58-encoded address of this transaction's source account
  + account_sequence (number, required) - The sequence number for this transaction and source account
  + max_fee (number, required)          - The maximum fee configured to be acceptable to this transaction
  + fee_paid (number, required)         - The actual fee paid by this transaction's source account during application to the ledger
  + operation_count (number, required)  - The number of operations that are encoded into this transaction
  + result_code (number, required)      - The result code for the application of this transaction to the ledger
  + result_code_s (string, required)    - The string representation of the result code
  + envelope_xdr (string, required)     - The base64-encoded XDR representation of the original TransactionEnveleop
  + result_xdr (string, required)       - The base64-encoded XDR representation of the TransactionResultPair returned during application
  + result_meta_xdr (string, required)  - The base64-encoded XDR representation of the TransactionMeta created during transaction application


### View transaction's details [GET]

  + Parameters

    + hash (required, string, `0ab231385734ad4092cc0651f3acd2a6e3eead24282f2725a79d019d4b791d54`) ... The hex-encoded hash of a transaction

  + Response 200

      + Attributes (Transaction)

## Transaction Collection [/transactions{?order}{?limit}{?after}]

+ Model (application/hal+json)

        {
          "_links": {
            "next": {
              "href": "/transactions?after=373a31&limit=1&order=asc"
            }
          },
          "_embedded": {
            "records": [
              {
                "_links": {
                  "self": {
                    "href": "/transactions/0ab231385734ad4092cc0651f3acd2a6e3eead24282f2725a79d019d4b791d54"
                  },
                  "account": {
                    "href": "/accounts/gM4gu1GLe3vm8LKFfRJcmTt1eaEuQEbo61a8BVkGcou78m21K7"
                  }
                },
                "hash": "0ab231385734ad4092cc0651f3acd2a6e3eead24282f2725a79d019d4b791d54",
                "ledger": 7,
                "application_order": [
                  7,
                  1
                ],
                "account": "gM4gu1GLe3vm8LKFfRJcmTt1eaEuQEbo61a8BVkGcou78m21K7",
                "account_sequence": 1,
                "max_fee": 10,
                "fee_paid": 10,
                "operation_count": 1
              }
            ]
          }
        }

### View a page of transaction history [GET]

  + Parameters
    + after (optional, string, `373a31`) ... A paging token
    + limit (optional, number, `10`) ... The maximum number of transactions to return in the response
    + order (string)

        The order to traverse the transaction collection

        + Values
            + `asc`
            + `desc`

  + Response 200

    [Transaction Collection][]


### Submitting a transaction [POST]

  + Request (application/x-www-form-urlencoded)

        tx=fffff

  + Response 200 (application/hal+json)

        {}


# Data Structures

## Date (string)

An ISO8601 string representation of a time

### Sample

"2012-06-30T13:15:00Z"

### Sample

"2015-06-12T08:15:10.12345Z"

## Resource (object)

+ Attributes
  + id (string, required)                 - An opaque identifier for this resource
  + paging_token (string, required)       - An opaque cursor, which may be used for paging through the collection (i.e. used as the cursor parameter)
